name: Bike Share Project Deployment
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Bike Share project Docker build."]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # - name: Download artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: VERSION
      # - name: Download artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: VERSION

      # - name: Read version
      #   run: echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_ENV
      # - name: Read version
      #   run: echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_ENV
               
      - name: Pull the  docker image which build on ci.ymal
        run: |
          sudo docker pull ${{ secrets.DOCKERHUB_UNAME }}/bike_sharing_api:0.0.2
        # sudo docker pull ${{ secrets.DOCKERHUB_UNAME }}/bike_sharing_api:${{vars.VERSION}}
        
      - name: Run bikesharing api image
        run: |
          sudo docker run -d -p 8001:8001 --name bikeshare_app yogishil/bikeshare_model_api:0.0.2

        # sudo docker run -d -p ${{vars.BIKESHARE_API_PORT}}:${{vars.BIKESHARE_API_PORT}} ${{ secrets.DOCKERHUB_UNAME }}/bike_sharing_api:${{vars.VERSION}}
          
  
      
